q1 : q1.o IntegerArray.o
	g++ -Wall -g q1.o IntegerArray.o -o execute

q1.o : q1.cpp IntegerArray.h
	g++ -Wall -g -c q1.cpp 

IntegerArray.o: IntegerArray.cpp IntegerArray.h
	g++ -Wall -g -c IntegerArray.cpp
